### ISSUE TITLE
UNMET PEER DEPENDENCY yo@>=1.0.0

### ISSUE THREAD

**Issue by mariusz** [keystonejs/generator-keystone#139]
Trying to install Keystone from scratch on a new Node version I am getting this error:

    └── UNMET PEER DEPENDENCY yo@>=1.0.0

    npm WARN EPEERINVALID generator-keystone@0.3.9 requires a peer of yo@>=1.0.0 but none was installed.

Meanwhile, `yo` is installed and incredibly fresh: 

    15:41 ~/% yo --version
    1.5.0

Any ideas how to make this work?

**Comment by creynders** [comment]
If I'm not mistaken the generator should've finished properly though. It's just a warning.
If not however, I assume your `npm` version is less than 3? Then you should definitely update `npm` since they've tried to fix the _severely_ broken peer dependency system of v2 (on a sidenote: I'm not entirely convinced they succeeded)

**Comment by kabojnk** [comment]
I am having this issue as well.  npm version 3.3.8, yo 1.5.0.

**Comment by creynders** [comment]
Yeah, I haven't had time to delve into the new v3 specifics of peer dependencies, but I assume that since npm doesn't auto-install peer dependencies any more (fortunately!) and it tries to resolve them locally it won't recognise the globally installed `yo`. I don't know what the appropriate way to declare a global peer dependency is now though...
