### ISSUE TITLE
RFC: Replace Swig with Twig

### ISSUE THREAD

**Issue by mxstbr** [keystonejs/generator-keystone#180]
> Swig is no longer maintained: paularmstrong/swig#628

> Its arguably inferior to Twig.js, which is actively maintained and supports cacheing and a host of other improvements over swig.

> This RFC is a proposal to replace swig with Twig as an option for templating language. If accepted, i will do the PR as this is very important for my team.

Continued from https://github.com/keystonejs/keystone/issues/2784

**Comment by mxstbr** [comment]
I didn't know that Swig isn't maintained anymore, thus it makes sense to remove it.

I'm not sure if replacing it with Twig is the way to go here though, because that's another templating language setup that we have to maintain. (which is a pain since we don't use those templating languages)

Maybe @JedWatson has some comments here?

**Comment by r3wt** [comment]
well, Swig is based on the original Twig templating language, as is Twig.js. so in likelyhood there would be no change other than the implementation of the loading of templates and render method. Swig deviates from the standard Twig syntax in some instances.

Also, would it change your mind if I vowed to maintain the templates? If no, i certainly understand and harbor no ill will.

**Comment by mxstbr** [comment]
> I vowed to maintain the templates

You know that goes, can't force anybody to maintain open source in their free time. :)

I appreciate the offer, and I understand the reasoning. I don't mind either way, but lets have @JedWatson have the last call since he's been the main dev behind the generator.

**Comment by morenoh149** [comment]
less is more. I'm starting to question the value of providing so many templating language choices in the generator at all. How about ejs, or pug. And document very very well how to swap out the templating language for anything else?

**Comment by mxstbr** [comment]
Agree with @morenoh149, that'd make sense imo.

**Comment by r3wt** [comment]
@morenoh149 which is all great if Keystone uses your favorite templating language, but if it doesn't you're SOL. As for your comment "how about ejs or pug":

**Well, how about Twig?**

Twig is good for traditional MVC developers who want a feature complete templating engine completely seperated from the controller/model, with security on by default. its the same as swig except for the swig author(s) deviated from the spec of Twig in some ways, and Twig has compiled template cacheing, as is in my opinion a better codebase. the current swig views should be compatible with Twig already.

**Comment by mxstbr** [comment]
No you're not, swapping in your favorite templating language isn't hard. We only provide three implementations for fun, but putting in your templating language of choice is actually pretty easy. (do a diff on our different implementations)

**Comment by JedWatson** [comment]
@r3wt Paul Armstrong recommends nunjucks in that deprecation issue, which we also have. I haven't had a chance to compare it with Swig / Twig closely, what's your view on that? Is having nunjucks good enough or does Twig present a compelling reason to support another template in the generator?

As you can tell from the other maintainer comments, we've had a fair bit of overhead in the project because we've had so many variations on template languages (including less/sass) to maintain equity between.

Having said that, handlebars has really been the painful one... it was contributed and not fully functional, it's been haunting me ever since (and isn't even something I need/use/want, which sucks a bit) - it's also the most different from the other three, which makes maintaining it hard.

If you're really up for contributing + maintaining the Twig templates, I'm more happy for that than @mxstbr or @morenoh149 have sounded, but want to make sure you know what you're getting yourself into :)

**Comment by r3wt** [comment]
@JedWatson I already have this underway locally. so far i've only needed to make a few minor changes to `keystone.js`.

`var Twig = require('twig');`
keystone.init: 
```js
'view engine': 'twig',
'twig options':{ method: 'fs' },
'custom engine':Twig.render,
```
I'm currently working on editing the templates. can you clarify the shape of the template arguments being passed into the render mechanism? i don't seem to be getting any variables in my template.

**Comment by r3wt** [comment]
I should clarify the reason i use Twig.js:

- Mature based on Symfony's Twig Template Language, since 2009.
- Active Development.
- good perf in node
- Portable to PHP (and Python(Jinja) and Ruby(Liquid) with minimal effort)

it does have some drawbacks:
- high perf cost for initial render
- no autoreload of templates
- implementation lacks 100% coverage.

**Comment by mxstbr** [comment]
If you've got it done anyway, I'd love to see a PR! :+1:

**Comment by r3wt** [comment]
I'm working on cleaning it up and testing. I'll submit the PR when i get home from church.

**Comment by r3wt** [comment]
@mxstbr Ok, so i've opened a PR. i'm unsure how i can test this? Could you offer some advice. I'm literally brand new to generators and modules in general, so i'm unsure how i could test this?

**Comment by mxstbr** [comment]
I don't actually know either! Running the generator, choosing Twig and verifying that everything works as before would be a good one…

**Comment by r3wt** [comment]
@mxstbr ok, so i've been testing and i've ran into some potential issues:

- macros cannot be called from the context of other macros, so flash messages arent working.
- utils appears to not be imported, or if it is, `utils.isObject()` is not working as expected. in order to use a function in twig js, `Twig.extendFunction(name,fn);` should be used. I'm going to hack on this later this evening. i won't submit another PR until i've solved all issues.

**Comment by mxstbr** [comment]
> so flash messages arent working.

Are you using the latest `master` version of keystone? Flash messages don't exist anymore…

**Comment by r3wt** [comment]
I'm using whatever comes with generator-keystone!

**Comment by morenoh149** [comment]
The generator still loads in 0.3x unsurprisingly. But if flash is lacking in the 4x line you can ignore that. Actually it may be cool to release a generator that loads 4x at the same time 4x is released!

**Comment by r3wt** [comment]
My PR fails. attempting to select twig in the generator results in jade being selected. debugging now.

**Comment by r3wt** [comment]
https://github.com/keystonejs/generator-keystone/commit/988fa0b8a0645624435b16bb5ec5758db14c8d30 and https://github.com/keystonejs/generator-keystone/commit/8371ccf16cf063e6856b39a5f39d180bad4a07dd

**Comment by brundonsmith** [comment]
Does anyone know about the status of template autoreloading? Just started a new Keystone project with the Twig update after finishing one with Swig, and the lack of template reloading is a pretty big hang up for development...

**Comment by brundonsmith** [comment]
As a temporary solution for those who have the same problem, adding the following to `nodemon.json` will make it restart on twig template changes:
```
{
  "ext": "twig"
}
```
