### ISSUE TITLE
Deprecated includes...

### ISSUE THREAD

**Issue by MB34** [keystonejs/generator-keystone#277]
Running: npm install -g generator-keystone

```
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated simple-bufferstream@0.0.4: no longer maintained
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
+ generator-keystone@0.5.1
added 236 packages from 148 contributors in 24.948s
```
You gonna fix these in the generator install?

**Comment by stennie** [comment]
@MB34 Yes, these will be resolved by way of issue  #281. Most of the current warnings & deprecations are because an older version of `yeoman-generator` is specified in the `package.json` (0.17.7 versus the latest release which is 3.1.1). It looks like some changes are required to update to the latest package API.

Note: these `npm` warnings are specific to `yo keystone` (the Keystone Generator) and not the deployment of Keystone 4 that the generator creates.
